// This file is auto-generated by scripts/generate-presentations.mjs
// Do not edit this file manually.

import type { PresentationMeta } from './presentation-meta';

export const generatedPresentations: PresentationMeta[] = [
  {
    id: "ai-mentoring-1",
    title: "Ai Mentoring (1)",
    path: "/slides/ai-mentoring%20(1).html",
    updatedAt: "2026-04-06",
    thumbnail: "/slides/.thumbnails/ai-mentoring%20(1).png",
  },
];
