// This file is auto-generated by scripts/generate-presentations.mjs
// Do not edit this file manually.

import type { PresentationMeta } from './presentation-meta';

export const generatedPresentations: PresentationMeta[] = [
  {
    id: "ai-cli-start-guide",
    title: "Ai Cli Start Guide",
    path: "/slides/ai-cli-start-guide.html",
    updatedAt: "2026-04-08",
    thumbnail: "/slides/.thumbnails/ai-cli-start-guide.png",
  },
  {
    id: "ai-mentoring-1",
    title: "Ai Mentoring (1)",
    path: "/slides/ai-mentoring%20(1).html",
    updatedAt: "2026-04-06",
    thumbnail: "/slides/.thumbnails/ai-mentoring%20(1).png",
  },
  {
    id: "economic-terms-10",
    title: "Economic Terms 10",
    path: "/slides/economic-terms-10.html",
    updatedAt: "2026-04-06",
    thumbnail: "/slides/.thumbnails/economic-terms-10.png",
  },
  {
    id: "presentation",
    title: "Presentation",
    path: "/slides/presentation.html",
    updatedAt: "2026-04-15",
    thumbnail: "/slides/.thumbnails/presentation.png",
  },
];
